-- Core
require('settings')
require('keymaps')
require('colors')

-- Plugins
require('plugins.packer')
require('plugins.impatient')
require('plugins.nvim-tree')
require('plugins.bufferline')
require('plugins.telescope')
require('plugins.cmp')
require('plugins.treesitter')
require('plugins.project')
require('plugins.lsp')
require('plugins.lualine')
require('plugins.neogit')
require('plugins.gitsigns')
require('plugins.git-blame')
require('plugins.toggleterm')
require('plugins.autopairs')
require('plugins.comment')
require('plugins.indent')
require('plugins.hop')
require('plugins.neoscroll')
require('plugins.gps')
require('plugins.autosave')
require('plugins.spectre')
require('plugins.whichkey')
